sudo: required

language: php

matrix:
  include:
    - php: 5.2
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 5.6
      env: DB=MySQL5.1
    - php: 7.0
    - php: hhvm

  allow_failures:
    - php: hhvm

env:
  - WP_VERSION=nightly WP_MULTISITE=0
  - WP_VERSION=nightly WP_MULTISITE=1

# Clones WordPress and configures our testing environment.
before_script:
  - phpenv local 5.5
  - composer install --no-interaction
  - phpenv local --unset

  - >
    if [[ "$DB" == "MySQL5.1" ]]; then
      bash bin/install-wp-tests.sh wordpress_test travis travil 127.0.0.1:3310 $WP_VERSION
    else
      bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 $WP_VERSION
    fi

script:
  - phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    rooms:
      secure: m8wmVqRIg/S7oH5GDDmzyavlrzbQv0cX0JG9Yo8LKLNelcHEZj95a7Qvmwf/hIKwCgPfeFdq/Gy8BnQDRmfpZ255J7S/JoYIRCGcJ6CVv/EY0ijP5617+cgmHoj4TgApn3+wzkh2sfckJqI161mmrGnJM2ZQTi/NZXH8fKkcmTjSKa0Bo/GqwJS/o0SLfQuSlbRWIFb7iYmAQPCl4Aj1v/HnVX7AjJPKqmytcvWUdTTSRbEma3MufD7KgTQmdMASbd72pEevTIsaohvRnV1mM8niRD254ny31hKSBvoNW2dg/hD0a0a89i70AsIzvCQ5/d1adLCzbDPwQA0MTw7/3AMp9x3BcKy88MA/LdiIvh7xUXL7zJ+v0pDbRBBzvRT++WXEUSAZfh6XfuvxScNJE0dAjLbylksEFA6VW2A23ojJ0F6wbZqt5W04WZh56wkwWF8xE+441psfC2hDzGuqsZFTdViZt0Z4pYg+sCjt6rKCZs9/qLT3AtrYsuqHm4Tmt0Jc5oagXje25kuq04L6iWSqlOnaV8QBajRKgX2TSLNSrwLf9BxysG/Ef3JuO3LpjQGUMlJiigymhZRV3DbmcvePFu5hVHcIitoQjgUY11eVil69y32WGvLGAu3X1nzbpsm6+43M/ebR2y0OJDOqTJ5aC1gqI5kVvYwmnillkiw=
    on_start: never
    on_failure: always
    on_success: change
